services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME:-shift_crm}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
  